from typing import Callable

def resolve(value: list[set[int]], weight: list[int], calc_distance: Callable[[int, int], int] | None = None): ...
def resolve_rec(value: list[set[int]], weight: list[int], calc_distance: Callable[[int, int], int] | None = None): ...
def resolve_rec_spawn(
    value: list[set[int]], weight: list[int], calc_distance: Callable[[int, int], int] | None = None
): ...
def resolve_rec_rayon(
    value: list[set[int]], weight: list[int], calc_distance: Callable[[int, int], int] | None = None
): ...
